#!/usr/bin/env python3
import os
import sys

from analyzer import Analyzer
from termcolor import colored
import helpers

def main():
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @screen_name")
    
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")
        
    analyzer = Analyzer(positives, negatives)
        
    screen_name = sys.argv[1].strip('@')
        
    tweets = helpers.get_user_timeline(sys.argv[1])
        
    if tweets == None:
        sys.exit("username error. Maybe private or does not exist")
        
    for tweet in tweets:
        score = analyzer.analyze(tweet)
        if score > 0.0:
            print(colored("{}".format(tweet), "green"))
        elif score < 0.0:
            print(colored("{}".format(tweet), "red"))
        else:
            print(colored("{}".format(tweet), "yellow"))

if __name__ == "__main__":
    main()

    
    
